### ISSUE TITLE
1) OSI 7계층 질문에서 계층 설명이 보기 불편하다.

### ISSUE THREAD

**Issue by bumsly** [in-ch/tech-inverview-study#45]
1. 계층 정보 개행이 빠져있음. 
2. 이미지로 추가가능하다면 이미지로 추가
3. Network 폴더로 이동

**Comment by in-ch** [comment]
![스크린샷 2024-01-08 오후 9 36 30](https://github.com/in-ch/tech-inverview-study/assets/49556566/b5d083d4-2292-4ed6-a1eb-d8ac143d8beb)
